blank_issues_enabled: true
contact_links:
  - name: ğŸ–ï¸ Yii Community
    url: https://www.yiiframework.com/community
    about: A friendly and helpful Yii community
  - name: â“ Forum
    url: https://forum.yiiframework.com
    about: Please use the Yii forum for questions
