blank_issues_enabled: true
contact_links:
  - name: ğŸ–ï¸ Yii Community
    url: https://www.yiiframework.com/community
    about: A friendly and helpful Yii community
  - name: ğŸ—ª Yii Slack channel
    url: https://yiiframework.com/go/slack
    about: Yii Slack channel
  - name: â“ YiiÂ½ Forum
    url: https://forum.yiiframework.com
    about: Please use the Yii forum for questions regarding Yii 1 / 2
  - name: â“ Yii3 Forum
    url: https://forum.yiiframework.com/c/yii-3-0/63
    about: Please use the Yii3 forum for questions regarding Yii 3
