blank_issues_enabled: true
contact_links:
  - name: ğŸ–ï¸ Yii Community
    url: https://www.yiiframework.com/community
    about: A friendly and helpful Yii community
  - name: ğŸ—ª Yii Ask questions on Slack
    url: https://yiiframework.com/go/slack
    about: Yii Slack channel
  - name: ğŸ™‹ Yii Telegram
    url: https://t.me/yii3en
    about: Yii Telegram channel
  - name: ğŸ™‹ Yii3 Forum
    url: https://forum.yiiframework.com/c/yii-3-0/63
    about: Please use the forum for questions regarding Yii3
